#!/bin/bash

# Location-Based Alarm Condition Testing Script
# This script helps you test all location-based smart control conditions

echo "🔍 Location-Based Alarm Condition Testing Guide"
echo "=================================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}📱 Pre-Testing Setup:${NC}"
echo "1. Enable location permissions for the app"
echo "2. Make sure GPS is enabled on device"
echo "3. Connect device to computer for ADB logging"
echo "4. Open Android Studio Logcat or run: adb logcat -s LocationCondition"
echo ""

echo -e "${YELLOW}🧪 Testing Strategy:${NC}"
echo "We'll test each condition type by:"
echo "• Setting an alarm with the condition"
echo "• Moving to different locations relative to target"
echo "• Observing the alarm behavior when it triggers"
echo ""

echo -e "${GREEN}📍 Test Locations Setup:${NC}"
echo "Choose a target location (e.g., your home/office) and plan these test positions:"
echo "• Position A: WITHIN 500m of target (e.g., same building/nearby)"
echo "• Position B: BEYOND 500m of target (e.g., different neighborhood)"
echo ""

echo -e "${RED}⚠️  Important Testing Notes:${NC}"
echo "• Set alarm times 2-3 minutes in future for quick testing"
echo "• Wait for GPS to get accurate location fix before testing"
echo "• Check logcat output for detailed condition evaluation"
echo "• Test both positions (within/beyond 500m) for each condition"
echo ""

echo "=================================================="
echo "🔄 CONDITION 1: OFF (Index 0)"
echo "=================================================="
echo "Expected: Alarm always rings (location ignored)"
echo ""
echo "Test Steps:"
echo "1. Create alarm with location condition OFF"
echo "2. Set alarm 2 minutes in future"
echo "3. Wait for alarm"
echo ""
echo "✅ Expected Result: Alarm rings regardless of location"
echo "📝 Logcat Look For: 'Location condition is off, alarm rings normally'"
echo ""

echo "=================================================="
echo "🎯 CONDITION 2: RING WHEN AT (Index 1)"
echo "=================================================="
echo "Expected: Ring ONLY when within 500m of target location"
echo ""
echo "Test A - Within Range:"
echo "1. Go to Position A (within 500m of target)"
echo "2. Create alarm with 'Ring when AT location'"
echo "3. Select your target location on map"
echo "4. Set alarm 2 minutes in future"
echo "5. Stay within 500m and wait"
echo ""
echo "✅ Expected Result: Alarm RINGS"
echo "📝 Logcat Look For: 'Alarm is ringing. You are XXXm from chosen location (within 500m)'"
echo ""
echo "Test B - Beyond Range:"
echo "1. Go to Position B (beyond 500m of target)"
echo "2. Create alarm with 'Ring when AT location'"
echo "3. Select your target location on map"
echo "4. Set alarm 2 minutes in future"
echo "5. Stay beyond 500m and wait"
echo ""
echo "❌ Expected Result: Alarm DOES NOT ring"
echo "📝 Logcat Look For: 'Alarm didn't ring. You are XXXm away from chosen location (beyond 500m)'"
echo ""

echo "=================================================="
echo "🚫 CONDITION 3: CANCEL WHEN AT (Index 2)"
echo "=================================================="
echo "Expected: Ring ONLY when beyond 500m of target location"
echo ""
echo "Test A - Within Range:"
echo "1. Go to Position A (within 500m of target)"
echo "2. Create alarm with 'Cancel when AT location'"
echo "3. Select your target location on map"
echo "4. Set alarm 2 minutes in future"
echo "5. Stay within 500m and wait"
echo ""
echo "❌ Expected Result: Alarm DOES NOT ring"
echo "📝 Logcat Look For: 'Alarm didn't ring. You are only XXXm away from chosen location'"
echo ""
echo "Test B - Beyond Range:"
echo "1. Go to Position B (beyond 500m of target)"
echo "2. Create alarm with 'Cancel when AT location'"
echo "3. Select your target location on map"
echo "4. Set alarm 2 minutes in future"
echo "5. Stay beyond 500m and wait"
echo ""
echo "✅ Expected Result: Alarm RINGS"
echo "📝 Logcat Look For: 'Alarm is ringing. You are XXXm away from chosen location'"
echo ""

echo "=================================================="
echo "🏃 CONDITION 4: RING WHEN AWAY (Index 3)"
echo "=================================================="
echo "Expected: Ring ONLY when beyond 500m of target location"
echo ""
echo "Test A - Within Range:"
echo "1. Go to Position A (within 500m of target)"
echo "2. Create alarm with 'Ring when AWAY from location'"
echo "3. Select your target location on map"
echo "4. Set alarm 2 minutes in future"
echo "5. Stay within 500m and wait"
echo ""
echo "❌ Expected Result: Alarm DOES NOT ring"
echo "📝 Logcat Look For: 'Alarm didn't ring. You are only XXXm from chosen location (within 500m)'"
echo ""
echo "Test B - Beyond Range:"
echo "1. Go to Position B (beyond 500m of target)"
echo "2. Create alarm with 'Ring when AWAY from location'"
echo "3. Select your target location on map"
echo "4. Set alarm 2 minutes in future"
echo "5. Stay beyond 500m and wait"
echo ""
echo "✅ Expected Result: Alarm RINGS"
echo "📝 Logcat Look For: 'Alarm is ringing. You are XXXm away from chosen location (beyond 500m)'"
echo ""

echo "=================================================="
echo "🛑 CONDITION 5: CANCEL WHEN AWAY (Index 4)"
echo "=================================================="
echo "Expected: Ring ONLY when within 500m of target location"
echo ""
echo "Test A - Within Range:"
echo "1. Go to Position A (within 500m of target)"
echo "2. Create alarm with 'Cancel when AWAY from location'"
echo "3. Select your target location on map"
echo "4. Set alarm 2 minutes in future"
echo "5. Stay within 500m and wait"
echo ""
echo "✅ Expected Result: Alarm RINGS"
echo "📝 Logcat Look For: 'Alarm is ringing. You are XXXm from chosen location (within 500m)'"
echo ""
echo "Test B - Beyond Range:"
echo "1. Go to Position B (beyond 500m of target)"
echo "2. Create alarm with 'Cancel when AWAY from location'"
echo "3. Select your target location on map"
echo "4. Set alarm 2 minutes in future"
echo "5. Stay beyond 500m and wait"
echo ""
echo "❌ Expected Result: Alarm DOES NOT ring"
echo "📝 Logcat Look For: 'Alarm didn't ring. You are XXXm away from chosen location (beyond 500m)'"
echo ""

echo "=================================================="
echo "🔧 DEBUGGING COMMANDS"
echo "=================================================="
echo ""
echo "Monitor location condition logs:"
echo "adb logcat -s LocationCondition"
echo ""
echo "Monitor all alarm-related logs:"
echo "adb logcat -s AlarmReceiver:D LocationCondition:D LocationFetcherService:D"
echo ""
echo "Clear logcat before each test:"
echo "adb logcat -c"
echo ""
echo "Check if location services are working:"
echo "adb logcat -s Location"
echo ""

echo "=================================================="
echo "📊 TEST RESULT TRACKING"
echo "=================================================="
echo ""
echo "Create a simple test log:"
echo ""
echo "Test #1 - OFF:"
echo "  ✅/❌ Alarm rings regardless of location"
echo ""
echo "Test #2A - RING_WHEN_AT (within 500m):"
echo "  ✅/❌ Alarm rings when close"
echo ""
echo "Test #2B - RING_WHEN_AT (beyond 500m):"
echo "  ✅/❌ Alarm doesn't ring when far"
echo ""
echo "Test #3A - CANCEL_WHEN_AT (within 500m):"
echo "  ✅/❌ Alarm doesn't ring when close"
echo ""
echo "Test #3B - CANCEL_WHEN_AT (beyond 500m):"
echo "  ✅/❌ Alarm rings when far"
echo ""
echo "Test #4A - RING_WHEN_AWAY (within 500m):"
echo "  ✅/❌ Alarm doesn't ring when close"
echo ""
echo "Test #4B - RING_WHEN_AWAY (beyond 500m):"
echo "  ✅/❌ Alarm rings when far"
echo ""
echo "Test #5A - CANCEL_WHEN_AWAY (within 500m):"
echo "  ✅/❌ Alarm rings when close"
echo ""
echo "Test #5B - CANCEL_WHEN_AWAY (beyond 500m):"
echo "  ✅/❌ Alarm doesn't ring when far"
echo ""

echo "=================================================="
echo "🎯 QUICK TEST SUMMARY"
echo "=================================================="
echo ""
echo "Condition Logic Summary:"
echo "• RING_WHEN_AT: Ring if WITHIN 500m"
echo "• CANCEL_WHEN_AT: Ring if BEYOND 500m"  
echo "• RING_WHEN_AWAY: Ring if BEYOND 500m"
echo "• CANCEL_WHEN_AWAY: Ring if WITHIN 500m"
echo ""
echo "Remember: The 500m radius is fixed and cannot be changed in current implementation."
echo ""
echo "Happy Testing! 🧪" 