#!/bin/bash

# Weather-Based Alarm Condition Testing Script
# This script helps you test all weather-based smart control conditions

echo "🌤️ Weather-Based Alarm Condition Testing Guide"
echo "================================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}📱 Pre-Testing Setup:${NC}"
echo "1. Enable location permissions for the app"
echo "2. Make sure internet connection is available"
echo "3. Connect device to computer for ADB logging"
echo "4. Open Android Studio Logcat or run: adb logcat -s WeatherFetcherService WeatherCondition Weather WeatherTypes WeatherMatch"
echo ""

echo -e "${YELLOW}🧪 Testing Strategy:${NC}"
echo "We'll test each condition type by:"
echo "• Setting an alarm with the specific weather condition"
echo "• Selecting weather types (sunny, cloudy, rainy, windy, stormy)"
echo "• Letting the alarm fire and observing the behavior"
echo "• Checking logs to see weather evaluation logic"
echo ""

echo -e "${GREEN}🌦️ Weather Condition Types Available:${NC}"
echo ""
echo "0️⃣  OFF - No weather condition (always rings)"
echo "1️⃣  RING_WHEN_MATCH - Ring alarm when current weather matches selected types"
echo "2️⃣  CANCEL_WHEN_MATCH - Cancel alarm when current weather matches selected types"
echo "3️⃣  RING_WHEN_DIFFERENT - Ring alarm when current weather is different from selected types"
echo "4️⃣  CANCEL_WHEN_DIFFERENT - Cancel alarm when current weather is different from selected types"
echo ""

echo -e "${GREEN}🌤️ Weather Types Available:${NC}"
echo ""
echo "0️⃣  SUNNY - Clear skies, no clouds, wind < 20km/h, no rain"
echo "1️⃣  CLOUDY - Cloud cover > 60%"
echo "2️⃣  RAINY - Rain > 0mm (but wind < 40km/h)"
echo "3️⃣  WINDY - Wind speed > 20km/h (but no rain)"
echo "4️⃣  STORMY - Rain > 0mm AND wind > 40km/h"
echo ""

echo -e "${YELLOW}📋 DETAILED TEST PLAN:${NC}"
echo ""

echo -e "${BLUE}=== Test 1: OFF Condition (Index 0) ===${NC}"
echo "📝 Expected: Alarm rings regardless of weather"
echo "📱 Setup:"
echo "   • Set weather condition to 'OFF'"
echo "   • Set alarm for 2 minutes from now"
echo "✅ Expected Result: Alarm should ALWAYS ring"
echo ""

echo -e "${BLUE}=== Test 2: RING_WHEN_MATCH (Index 1) ===${NC}"
echo "📝 Expected: Alarm rings only when weather matches selected types"
echo "📱 Setup:"
echo "   • Set weather condition to 'Ring When Match'"
echo "   • Select weather types (e.g., sunny, rainy)"
echo "   • Set alarm for 2 minutes from now"
echo "✅ Expected Result:"
echo "   • If current weather is sunny OR rainy → Alarm RINGS"
echo "   • If current weather is cloudy/windy/stormy → Alarm DOES NOT ring"
echo ""

echo -e "${BLUE}=== Test 3: CANCEL_WHEN_MATCH (Index 2) ===${NC}"
echo "📝 Expected: Alarm cancels when weather matches selected types"
echo "📱 Setup:"
echo "   • Set weather condition to 'Cancel When Match'"
echo "   • Select weather types (e.g., rainy, stormy)"
echo "   • Set alarm for 2 minutes from now"
echo "✅ Expected Result:"
echo "   • If current weather is rainy OR stormy → Alarm DOES NOT ring"
echo "   • If current weather is sunny/cloudy/windy → Alarm RINGS"
echo ""

echo -e "${BLUE}=== Test 4: RING_WHEN_DIFFERENT (Index 3) ===${NC}"
echo "📝 Expected: Alarm rings when weather is different from selected types"
echo "📱 Setup:"
echo "   • Set weather condition to 'Ring When Different'"
echo "   • Select weather types (e.g., sunny)"
echo "   • Set alarm for 2 minutes from now"
echo "✅ Expected Result:"
echo "   • If current weather is sunny → Alarm DOES NOT ring"
echo "   • If current weather is cloudy/rainy/windy/stormy → Alarm RINGS"
echo ""

echo -e "${BLUE}=== Test 5: CANCEL_WHEN_DIFFERENT (Index 4) ===${NC}"
echo "📝 Expected: Alarm cancels when weather is different from selected types"
echo "📱 Setup:"
echo "   • Set weather condition to 'Cancel When Different'"
echo "   • Select weather types (e.g., rainy, stormy)"
echo "   • Set alarm for 2 minutes from now"
echo "✅ Expected Result:"
echo "   • If current weather is rainy OR stormy → Alarm RINGS"
echo "   • If current weather is sunny/cloudy/windy → Alarm DOES NOT ring"
echo ""

echo -e "${RED}🚨 IMPORTANT LOG PATTERNS TO WATCH:${NC}"
echo ""
echo "✅ Success patterns:"
echo "   WeatherFetcherService: onStartCommand called"
echo "   WeatherFetcherService: Weather types JSON: [0,2], condition type: 1"
echo "   WeatherFetcherService: Converted weather types: sunny,rainy"
echo "   Weather: Current weather: sunny"
echo "   WeatherMatch: Weather matches selected types: true"
echo "   WeatherCondition: Ring when match: shouldRing = true"
echo ""
echo "❌ Error patterns to watch for:"
echo "   WeatherFetcherService: No network connectivity"
echo "   WeatherFetcherService: Failed to get location"
echo "   WeatherFetcherService: Weather API error"
echo "   WeatherFetcherService: Error parsing weather types"
echo ""

echo -e "${GREEN}🔧 TROUBLESHOOTING TIPS:${NC}"
echo ""
echo "❓ If weather condition doesn't trigger:"
echo "   • Check internet connection"
echo "   • Verify location permissions are granted"
echo "   • Look for WeatherFetcherService logs"
echo "   • Check if weather API is responding"
echo ""
echo "❓ If logs show 'Weather API error':"
echo "   • Check network connectivity"
echo "   • Wait a few minutes and try again"
echo "   • The app will default to ring on API failure"
echo ""
echo "❓ If weather evaluation seems wrong:"
echo "   • Check 'Current weather:' log"
echo "   • Verify 'Selected types:' matches your selection"
echo "   • Confirm 'Weather matches' logic is correct"
echo ""

echo -e "${BLUE}🎯 TESTING WORKFLOW:${NC}"
echo ""
echo "1. 🔧 Run log monitor: ./quick_weather_test.sh"
echo "2. 📱 Create alarm with weather condition in the app"
echo "3. ⏰ Wait for alarm to fire (2-3 minutes)"
echo "4. 📊 Observe logs and behavior"
echo "5. 📝 Record results in weather_test_results.md"
echo "6. 🔄 Repeat for each condition type"
echo ""

echo -e "${GREEN}⚡ QUICK TEST COMMANDS:${NC}"
echo ""
echo "Start log monitoring:"
echo "  ./quick_weather_test.sh"
echo ""
echo "Check current weather manually:"
echo "  adb logcat -s Weather WeatherCondition | grep 'Current weather'"
echo ""
echo "Clear logs before testing:"
echo "  adb logcat -c"
echo ""

echo -e "${YELLOW}📊 Ready to start testing!${NC}"
echo "Remember to document your results in weather_test_results.md"
echo "" 